---
- hosts: all
  become: false
  vars:
    version: "4.3.3"
    instance: "example" # will produce a "slapd-example" dir
    primary_suffix: "dc=example,dc=com"
    password: "secret"

  tasks:
  - name: install 389 Directory Service
    become: true
    yum:
      name: 389-ds-base
      state: latest
    register: ds389_install_state

  # as suggested by Red Hat Directory Server manual
  - name: add user 'dirsrv'
    become: true
    user:
      name: dirsrv
      comment: System user for 389DS
      system: true
      create_home: false

  - name: check if instance directory exists
    become: true
    stat:
      path: "/var/lib/dirsrv/slapd-{{ instance }}"
    register: instance_dir

  - set_fact:
      instance_dir_exists: "{{ instance_dir.stat.exists and instance_dir.stat.isdir }}"

  - name: copy 389ds_install.inf
    become: true
    template:
      src: install.inf.j2
      dest: /tmp/389ds_install.inf
      owner: dirsrv
      group: dirsrv
      mode: 0660
    when: not instance_dir_exists

  - name: execute install script
    become: true
    command: setup-ds.pl --silent --file=/tmp/389ds_install.inf
    args:
      creates: /var/lib/dirsrv/slapd-{{ instance }}

  - name: remove 389ds_install.inf (contains plaintext password)
    become: true
    file:
      path: /tmp/389ds_install.inf
      state: absent

  - name: execute update script (if a new version was installed)
    become: true
    command: setup-ds.pl --silent --update
    when: instance_dir_exists and ds389_install_state.changed

  - name: start and enable 389DS
    become: true
    service:
      name: dirsrv@{{ instance }}
      state: started
      enabled: yes
